#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "add-env ENV_NAME ACTIVATE_COMMAND"
    echo "Example:"
    echo "    add-env myenv"
    echo "    venv myenv"
    echo "    unenv"
    exit
fi


mkdir -p ~/app/virtualenv
virtualenv ~/app/virtualenv/$1

