#!/usr/bin/env bash

function envname() {
    echo ".env${1:6:3}"
}

function exist_env() {
    py=$1
    venvname=`envname $py`
    if [ ! -z `which $py` ] && [ -d "$venvname" ]; then
        echo $venvname
    fi
}

pythoncmds=( 'python3.6' 'python3.5' 'python3' 'python2' 'python' )

py=${@: -1}
if [ ! "${py:0:6}" == "python" ]; then
    py=
fi
if [ -z "$py" ]; then
    for py in "${pythoncmds[@]}"
    do
        if [ ! -z `exist_env $py` ]; then
            break
        fi
    done
    echo "Using default: $py"
fi
if [ "$1" == "delete" ]; then
    venvname=`exist_env $py`
    if [ -z $venvname ]; then
        echo "Virtual env for $py is not exists"
    else
        rm -rf $venvname
    fi
else
    if [ -z `exist_env $py` ]; then
        venvname=`envname $py`
        echo "Making virtual env (`which $py`)"
        virtualenv $venvname --python=`which $py`
    fi
    venvname=`exist_env $py`
    [[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo "To use env, type '. venv [python_command]'"
    source $venvname/bin/activate
fi
