set fileencodings=utf8,big5,gbk,latin1
set fileencoding=utf8
set <C-u>=^U
set <C-b>=^B
map <C-u> :set fileencoding=utf8
map <C-b> :set fileencoding=big5

set ai nu sw=4 ts=4 et sts=4
set backspace=indent,eol,start

set guifont=Monaco:h16
if has("gui_running")
    colorscheme koehler
else
    set background=dark
    colorscheme darkblue
endif
syntax on
filetype plugin indent on
set foldmethod=syntax
set foldlevel=10
set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

" Key mapping

let mapleader=","
map <Leader>n :tabnew<CR>
map <Leader>v :source $HOME/.vimrc<CR>
map <Leader><Left> :tabprev<CR>
map <Leader><Right> :tabnext<CR>
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
map <Leader>aii :set foldmethod=indent<CR>zM
map <Leader>ais :set foldmethod=syntax<CR>zM
map <Leader>p :set invpaste<CR>
" NERDCommenter
map <Leader>c <Plug>NERDCommenterToggle

"map <Leader>c 

" Configure

" NERDCommenter
let g:NERDSpaceDelims = 1

" airline
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_theme = 'luna'
let g:airline_exclude_preview = 1
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'
set laststatus=2
let g:airline_exclude_preview = 1 " Let airline focus right after preview is closed

" YouCompleteMe
let g:ycm_autoclose_preview_window_after_completion = 1

source $HOME/.vundle.vimrc

